default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: jake
#   pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: ostracized
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ostrich
  pool: 5